### ISSUE TITLE
This is not an issue but a question

### ISSUE THREAD

**Issue by Weedshaker** [SilentBot1/webtorrent-examples#1]
Hey SilentBot1,

your help was really great! Thanks again.

I am developing an app, at the moment in a private repo and I am planning to release it to a public github repo once all the groundwork has been done. 

Actually, the amount of work going into it has been a lot for a single person and I was wondering, if you would be interested on a side project? (I got a very early prototype here: http://starsystems.ch/webRTC.html)

Have a nice weekend!

**Comment by SilentBot1** [comment]
Hi @Weedshaker,

Helping was not a problem, I'm happy to help others. 

Before I can consider the request I would need to know more about the application, including:

- What are the goals and endgame of the application (what it aims to achieve)?
- What functionality should the finished application have (e.g. simple peer to peer chat)?
- What language('s) is the application written in?
- What is the intended time frame for the application?

From the prototype you linked it looks like a peer to peer messaging application using [RTCMultiConnection](https://github.com/muaz-khan/RTCMultiConnection). Is there anything I'm missing here?

Depending on the goals and aims of the project and weather they interest me, I would be happy to lend a helping hand, though I would need to balance this around University work meaning I may not always be able to contribute. 

I'm going to close the issue as it doesn't relate to any of the examples but feel free to continue to use it to chat with me.

All the best.

**Comment by Weedshaker** [comment]
Hello @SilentBot1 ,

1) Serving a website with frontend technology from a browser tab (desktop and mobile browser). To keep it short, like a xampp from the browser tab. Using WebRTC for realtime website and webtorrent for files (videos, etc.)

2) now it includes webrtc with diffing, shadow dom, webtorrent, summernote. There also shall be a service worker catching xhr's/fetchs, so that a react/angular, etc. app can be dropped into and served without much changes

3) ES6 using JSPM, but there is going to be a major junk of work for nodejs. (handshake server with search capabilities, etc.)

4) I have been working on it for approx. 1 year. There is no time limit, since it has been a hobby project besides my 100% job

it only uses webRTC data channels from muaz-khan's library. Although, I am going to switch it to simple peer. The RTCMultiConnection library is pretty bloated. But it helped kicking of development at first.

no problem, as I already mentioned, this is a hobby project. The reason why it hasn't been an open repo on github is, that I first want to lay down the solid basics. But I can add you on gitlab to my private repo.

Yes, please remove this issue. I just couldn't get in touch with you an other way. Could you, contact me at my profiles mail address, if you are still interested!? THX

Cheers
